### ISSUE TITLE
Could not pass event NationAddTownEvent to TownyDiscordChat v1.0.3

### ISSUE THREAD

**Issue by thejames10** [thejames10/TownyDiscordChat#3]
NationAddTownEvent fired!

[com.palmergames.bukkit.towny.Towny]: [Nation Msg] GoldenSpirit: The town of Bradfordshire joined the nation!

Could not pass event NationAddTownEvent to TownyDiscordChat v1.0.3

Console
12:52:53

```
     /**
     * Gets the Discord ID of the Player
     *
     * @param player Player to get the Discord ID from
     * @return The Discord ID or null when the player did not link their Discord
     */
    private static @Nullable String getLinkedId(@NotNull final Player player) {
        return DiscordSRV.getPlugin().getAccountLinkManager().getDiscordId(player.getUniqueId());
    }
```

java.lang.NullPointerException: null
at com.TownyDiscordChat.TownyDiscordChat.TDCManager.getLinkedId(TDCManager.java:1044) ~[?:?]
at com.TownyDiscordChat.TownyDiscordChat.TDCManager.givePlayerRole(TDCManager.java:767) ~[?:?]
at com.TownyDiscordChat.TownyDiscordChat.Listeners.TDCTownyListener.onTownJoinNation(TDCTownyListener.java:80) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor982.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-553]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-553]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-553]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-553]
at com.palmergames.bukkit.towny.object.Town.setNation(Town.java:227) ~[?:?]
at com.palmergames.bukkit.towny.command.NationCommand.nationAdd(NationCommand.java:1523) ~[?:?]
at com.palmergames.bukkit.towny.object.inviteobjects.TownJoinNationInvite.accept(TownJoinNationInvite.java:26) ~[?:?]
at com.palmergames.bukkit.towny.invites.InviteHandler.acceptInvite(InviteHandler.java:35) ~[?:?]
at com.palmergames.bukkit.towny.command.TownCommand.parseInviteCommand(TownCommand.java:850) ~[?:?]
at com.palmergames.bukkit.towny.command.TownCommand.parseTownCommand(TownCommand.java:669) ~[?:?]
at com.palmergames.bukkit.towny.command.TownCommand.onCommand(TownCommand.java:430) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-553]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-553]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-553]
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2023) ~[patched_1.16.5.jar:git-Paper-553]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1838) ~[patched_1.16.5.jar:git-Paper-553]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1791) ~[patched_1.16.5.jar:git-Paper-553]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Paper-553]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Paper-553]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-553]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-553]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-553]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-553]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-553]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1140) ~[patched_1.16.5.jar:git-Paper-553]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-553]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-553]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1094) ~[patched_1.16.5.jar:git-Paper-553]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1008) ~[patched_1.16.5.jar:git-Paper-553]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-553]
at java.lang.Thread.run(Thread.java:834) [?:?]

INFO
12:52:53

**Comment by thejames10** [comment]
A temp fix for this issue is to have the player run /tdc check role
